//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRestFull
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int SchoolId { get; set; }
    
        public virtual Schools Schools { get; set; }
    }
}
